export enum Role {
  ENFORCER = 'ENFORCER',
  GEARHEAD = 'GEARHEAD',
  STALKER = 'STALKER',
  FIXER = 'FIXER',
  DOG_HANDLER = 'DOG_HANDLER',
  CHRONICLER = 'CHRONICLER',
  BOSS = 'BOSS',
  SLAVE = 'SLAVE',
}
